{
    "name": "Certification",
    "summary": "Defines certification for different purposes",
    'version': '12.0.1.0.0',
    "category": "Certification Management",
    "website": "https://github.com/oca/RaulOForgeFlow",
    "author": "Grupo ESOC, Tecnativa, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "depends": ['base'],
    "data": ['security/ir.model.access.csv',
             'views/certification_view.xml',
             'views/certification_standard_view.xml',
             'views/certification_bodies_view.xml',
             'views/res_partner_view.xml',
             ],
    'demo':['data/certification_data.xml'],
    'development status': 'Beta',
    'maintainers': ['ceeficent'],
}
